#!/usr/bin/env python
import requests

params = {
#    'street': '123 Main 52001',
    'street': '200 S. Wacker Dr, Chicago, IL',
    'auth-id': 'e076f836-9fbb-4e0c-ab48-3325ea9959f9',
    'auth-token': 'Ws5ZeW0iNJz013SYnnZk'}
response = requests.get('https://api.smartystreets.com/street-address', params = params)

data = response.json()

for row in data:
    print row['components'][u'zipcode']




